name: Deploy Flutter Web via Actions

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Pub get
        run: flutter pub get

      - name: Build web (no PWA, correct base-href)
        run: flutter build web --release --base-href /responsive_app/ --pwa-strategy=none

      - name: Remove service worker (safety)
        run: rm -f build/web/flutter_service_worker.js build/web/flutter_service_worker.js.map

      - name: Patch bootstrap to disable SW registration (safety)
        run: sed -i 's/serviceWorkerVersion:[^,}]*/serviceWorkerVersion:null/g' build/web/flutter_bootstrap.js

      - name: Add 404.html for SPA routes
        run: cp build/web/index.html build/web/404.html

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/web

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4