name: Deploy Flutter Web to gh-packages

on: 
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flotter
        uses: subosito/flutter/action@v2
        with:
          channel: stable

      - name: Pub get
        run: flutter pub get

      - name : Build Web
        run: flutter build web --release --base-href /responsive_app/

      - name: Deploy to gh-packages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: build/web
          force_orphan: true