name: Deploy Flutter Web via Actions

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - run: flutter pub get

      
      - name: Build web (force HTML renderer via env)
        run: >
          flutter build web --release
          --base-href /responsive_app/ --pwa-strategy=none
          --dart-define=FLUTTER_WEB_RENDERER=html

      
      - name: Force correct <base href>
        run: sed -i 's#<base href="[^"]*"#<base href="/responsive_app/"#' build/web/index.html

      
      - run: rm -f build/web/flutter_service_worker.js build/web/flutter_service_worker.js.map
      - run: sed -i 's/serviceWorkerVersion:[^,}]*/serviceWorkerVersion:null/g' build/web/flutter_bootstrap.js || true

      
      - run: cp build/web/index.html build/web/404.html

      
      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with:
          path: build/web

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4